/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bonita.kafka.watcher;

import org.springframework.kafka.annotation.KafkaListener;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    @KafkaListener(topics = "orders", groupId = "")
    public void listen(String message) {
        System.out.println("Received Message in group foo: " + message);
    }
}
