kafka:
  bootstrap-servers: kafka:9092
  consumer:
    group-id: kafka-bonita-monitoring
    topics: orders,payments,shipments
bonita:
  server:
    url: http://172.23.0.1:8080
    username: walter.bates
    password: bpm
  target-process:
    name: New Order